### ISSUE TITLE
Need a help and discussion with models. 

### ISSUE THREAD

**Issue by Sidebail** [Sidebail/JS_BosJs#12]
I've stucked upon the issue where i want to provide the array of custom JS objects to mongooseSchema and im not sure if its a right path.

Also need to discuss with you what the better way to create items.

**Comment by Luis-Villafana-Tamez** [comment]
Would a nested JS object be different from an array?

**Comment by nathanielhf** [comment]
Could this be similar to how we provided Mongoose with Project objects in assignment one?

**Comment by Sidebail** [comment]
Irl we decided to make any logic within the controller file.
