### ISSUE TITLE
Set-up Node, PassportJS and Mongoose

### ISSUE THREAD

**Issue by Sidebail** [Sidebail/JS_BosJs#3]

**Comment by nathanielhf** [comment]
I'm beginning work on Mongoose. Doing the following
- create email account for BosJs (to be used by group members to administer Mongo Atlas cluster)
- create cluster in Mongo Atlas using group email account
- socialize group email credentials in slack
- install Mongoose
- connect app to Mongo cluster

- also waiting for email invite so I can push changes

**Comment by nathanielhf** [comment]
above work on Mongoose complete.

**Comment by nathanielhf** [comment]
Completed the following work on PassportJS
- implemented express-local to save session in client browser
- created basic user data model
- created register and login views
- built out auth routes and added authRouter to app.js
- auth routes save users to DB upon successful registration

**Comment by nathanielhf** [comment]
can possibly add auth with third-party apps (google, twitch, etc.) but basic functionality is complete, so closing for now.
